stages:
  - build
  - test
  - verify
  - deploy

variables:
  APP_NAME: "Kotlin-http4k"
  SEVERITIES: "HIGH"
  FAIL_THRESHOLD: 0

run_tests:
  image: gradle:jre11
  stage: test
  script:
    - CONTRAST__BASEURL=https://eval.contrastsecurity.com/Contrast/api/ng/$CONTRAST__ORG_ID;
    - curl --max-time 30 $CONTRAST__BASEURL/agents/default/java -H API-Key:$CONTRAST__API_KEY -H Authorization:$CONTRAST__AUTHORIZATION -o contrast.jar
    - curl --max-time 30 $CONTRAST__BASEURL/agents/external/default/java -H Accept:text/yaml -H API-Key:$CONTRAST__API_KEY -H Authorization:$CONTRAST__AUTHORIZATION -o contrast_security.yaml
    - ./gradlew build -Psha=$CI_COMMIT_SHORT_SHA

contrast_verify:
  image: cfmanteiga/alpine-bash-curl-jq:latest
  stage: verify
  script:
    - BASEURL="https://eval.contrastsecurity.com/Contrast/api/ng/$CONTRAST__ORG_ID"
    - CURLCMD="curl -HAccept:application/json -HAPI-Key:$CONTRAST__API_KEY -HAuthorization:$CONTRAST__AUTHORIZATION"
    - declare -a MYARRAY=$($CURLCMD -G --data-urlencode "filterText=$APP_NAME" "$BASEURL/applications/name")
    - APP_ID=$( echo ${MYARRAY[@]} | jq -r '.applications[0].app_id' )
    - echo ${MYARRAY[@]}
    - echo "The app id for the app called $APP_NAME is $APP_ID. Checking for $SEVERITIES vulnerabilities for the build commit $CI_COMMIT_SHORT_SHA."
    - declare -a MYARRAY=$($CURLCMD -G --data-urlencode "appVersionTags=$CI_COMMIT_SHORT_SHA" --data-urlencode "severities=$SEVERITIES" "$BASEURL/traces/$APP_ID/quick")
    - VULN_COUNT=$( echo ${MYARRAY[@]} | jq -r '.filters[1].count' )
    - echo "The vulnerability count is $VULN_COUNT."
    - if [ $VULN_COUNT -gt $FAIL_THRESHOLD ]; then exit 1; fi